// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBNNE_1dHtkga5oJhsY2G28elLLX5pp0A',
    appId: '1:495603617870:web:1745e667074a55d7ccf31f',
    messagingSenderId: '495603617870',
    projectId: 'e-voting-62074',
    authDomain: 'e-voting-62074.firebaseapp.com',
    storageBucket: 'e-voting-62074.appspot.com',
    measurementId: 'G-JD7J9EHXCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTxIdZ5BvMP41VjHviXSx8IevrpUvJzTo',
    appId: '1:495603617870:android:72ea6e3526961195ccf31f',
    messagingSenderId: '495603617870',
    projectId: 'e-voting-62074',
    storageBucket: 'e-voting-62074.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8cguiwvDNpiJoIYtyENg3x2FrsPB0QAA',
    appId: '1:495603617870:ios:a57fdd413a4c5102ccf31f',
    messagingSenderId: '495603617870',
    projectId: 'e-voting-62074',
    storageBucket: 'e-voting-62074.appspot.com',
    iosClientId: '495603617870-fljrgp61lfvhdfoa3b848ign7ep5p38d.apps.googleusercontent.com',
    iosBundleId: 'com.example.eVoting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8cguiwvDNpiJoIYtyENg3x2FrsPB0QAA',
    appId: '1:495603617870:ios:a57fdd413a4c5102ccf31f',
    messagingSenderId: '495603617870',
    projectId: 'e-voting-62074',
    storageBucket: 'e-voting-62074.appspot.com',
    iosClientId: '495603617870-fljrgp61lfvhdfoa3b848ign7ep5p38d.apps.googleusercontent.com',
    iosBundleId: 'com.example.eVoting',
  );
}
